/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LightsOut;

import hsa2.GraphicsConsole;
import java.awt.Color;
import java.awt.Point;

public class App {
    static int size = 5;

    static GraphicsConsole gc = new GraphicsConsole(600, 600, "Lights Out");

    static Grid gameBoard = new Grid(size, gc.getDrawWidth(), gc.getDrawHeight());

    public static void main(String[] args) {
        new App();
    }

    App() {
        // Setup
        gc.setAntiAlias(true);
        gc.setLocationRelativeTo(null);
        gc.setBackgroundColor(Color.black);
        gc.clear();
        gc.enableMouse();

        int tries = 0;

        // loop
        while (!gameBoard.isFull()) {
            if (gc.getMouseClick() >= 1) {
                int x = gc.getMouseX();
                int y = gc.getMouseY();

                Point loc = new Point(x, y);
                gameBoard.addressPoints(loc);

                tries++;
            }
            gameBoard.display(gc);
            gc.sleep(5);
        }

        // Winner!
        gc.clear();
        gc.print("Success in "+ tries +" tries!");

    }
}
